
version: '3.8'

services:
  # 1. Bizim Python Botu
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # 2. Celery için Haberleşme Sunucusu (Redis)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"